### ISSUE TITLE
Market data importer project

### ISSUE THREAD

**Issue by Robin-Warner** [Robin-Warner/portfolio-management#1]
# Tasks
- [x] Connect to yfinance: https://github.com/ranaroussi/yfinance/blob/main/README.md
- [ ] Test out different types of prices data that can be brought in (OHLC)
- [ ] Test out different asset classes that can be brought in (equity, gov bonds, corp bonds, ccy, commodities, etfs, options)
- [ ] Test out fundamental data that can be brought
- [ ] Test screening ability by asset class characteristics and fundamentals
